### ISSUE TITLE
Error while trying to get RedisGraph 

### ISSUE THREAD

**Issue by BRanganat** [RedisGraph/RedisGraph#560]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 16 Jul 2019 18:49:49.488 # Redis 5.0.5 crashed by signal: 11
1:M 16 Jul 2019 18:49:49.488 # Crashed running the instruction at: 0x7f891fecc529
1:M 16 Jul 2019 18:49:49.488 # Accessing address: (nil)
1:M 16 Jul 2019 18:49:49.488 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(abort+0x269)[0x7f891fecc529]

Backtrace:
/opt/bitnami/redis/bin/redis-server *:6379(logStackTrace+0x37)[0x558d4eb0a407]
/opt/bitnami/redis/bin/redis-server *:6379(sigsegvHandler+0xb0)[0x558d4eb0ab30]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0)[0x7f89202480e0]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x269)[0x7f891fecc529]
/lib/x86_64-linux-gnu/libc.so.6(+0x2be67)[0x7f891fec3e67]
/lib/x86_64-linux-gnu/libc.so.6(+0x2bf12)[0x7f891fec3f12]
/data/redisgraph.so(+0x602bf)[0x7f891db2c2bf]
/opt/bitnami/redis/bin/redis-server *:6379(moduleLoad+0x69)[0x558d4eb382f9]
/opt/bitnami/redis/bin/redis-server *:6379(moduleLoadFromQueue+0x33)[0x558d4eb38433]
/opt/bitnami/redis/bin/redis-server *:6379(main+0x42a)[0x558d4eabda4a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7f891feb82e1]
/opt/bitnami/redis/bin/redis-server *:6379(_start+0x2a)[0x558d4eabdd5a]

------ INFO OUTPUT ------
# Server
redis_version:5.0.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:24f9cd9802bc0a06
redis_mode:standalone
os:Linux 4.15.0-1042-azure x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:6.3.0
process_id:1
run_id:03d9d47b1cce7f3749f5b0b113ef023a9a3c79d4
tcp_port:6379
uptime_in_seconds:0
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:3021901
executable:/opt/bitnami/redis/bin/redis-server
config_file:/opt/bitnami/redis/etc/redis.conf

# Clients
connected_clients:0
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:0

# Memory
used_memory:793104
used_memory_human:774.52K
used_memory_rss:0
used_memory_rss_human:0B
used_memory_peak:793104
used_memory_peak_human:774.52K
used_memory_peak_perc:inf%
used_memory_overhead:791736
used_memory_startup:791736
used_memory_dataset:1368
used_memory_dataset_perc:100.00%
allocator_allocated:0
allocator_active:0
allocator_resident:0
total_system_memory:33707986944
total_system_memory_human:31.39G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:-nan
allocator_frag_bytes:0
allocator_rss_ratio:-nan
allocator_rss_bytes:0
rss_overhead_ratio:-nan
rss_overhead_bytes:0
mem_fragmentation_ratio:-nan
mem_fragmentation_bytes:0
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1563302989
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
aof_current_size:0
aof_base_size:0
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:0
total_commands_processed:0
instantaneous_ops_per_sec:0
total_net_input_bytes:0
total_net_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:7188da7ef0782a4b1d102aff186d93f9a6ed241c
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.023644
used_cpu_user:0.010565
used_cpu_sys_children:0.000897
used_cpu_user_children:0.004424

# Commandstats

# Cluster
cluster_enabled:0

# Keyspace

------ CLIENT LIST OUTPUT ------

------ REGISTERS ------
1:M 16 Jul 2019 18:49:49.489 #
RAX:0000000000000006 RBX:00007f8920d86000
RCX:00007f891fecafff RDX:0000000000000000
RDI:0000000000000002 RSI:00007ffe79223570
RBP:00007f891dbb5350 RSP:00007ffe79223680
R8 :0000000000000000 R9 :00007ffe79223570
R10:0000000000000008 R11:0000000000000246
R12:0000000000000037 R13:00007f891dbb6430
R14:00007f891fa097c0 R15:0000000000000000
RIP:00007f891fecc529 EFL:0000000000010246
CSGSFS:002b000000000033
1:M 16 Jul 2019 18:49:49.489 # (00007ffe7922368f) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe7922368e) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe7922368d) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe7922368c) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe7922368b) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe7922368a) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe79223689) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe79223688) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe79223687) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe79223686) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe79223685) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe79223684) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe79223683) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe79223682) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe79223681) -> 0000000000000000
1:M 16 Jul 2019 18:49:49.489 # (00007ffe79223680) -> 0000000000000020

------ FAST MEMORY TEST ------
1:M 16 Jul 2019 18:49:49.489 # Bio thread for job type #0 terminated
1:M 16 Jul 2019 18:49:49.490 # Bio thread for job type #1 terminated
1:M 16 Jul 2019 18:49:49.490 # Bio thread for job type #2 terminated
*** Preparing to test memory region 558d4ee40000 (2252800 bytes)
*** Preparing to test memory region 558d50212000 (135168 bytes)
*** Preparing to test memory region 7f891bac9000 (8388608 bytes)
*** Preparing to test memory region 7f891c2ca000 (8388608 bytes)
*** Preparing to test memory region 7f891cacb000 (8388608 bytes)
*** Preparing to test memory region 7f891d2cc000 (8388608 bytes)
*** Preparing to test memory region 7f891ddfc000 (4096 bytes)
*** Preparing to test memory region 7f891ddfe000 (8388608 bytes)
*** Preparing to test memory region 7f891e5ff000 (8388608 bytes)
*** Preparing to test memory region 7f891ee00000 (8388608 bytes)
*** Preparing to test memory region 7f891f600000 (8388608 bytes)
*** Preparing to test memory region 7f8920233000 (16384 bytes)
*** Preparing to test memory region 7f8920450000 (16384 bytes)
*** Preparing to test memory region 7f8920d7c000 (32768 bytes)
*** Preparing to test memory region 7f8920d86000 (4096 bytes)
*** Preparing to test memory region 7f8920d89000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: abort (base: 0x7f891fecc2c0)
Module: /lib/x86_64-linux-gnu/libc.so.6 (base 0x7f891fe98000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x7f891fecc2c0 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
1:M 16 Jul 2019 18:49:49.758 # dump of function (hexdump of 745 bytes):
4881ec2801000064488b142510000000483b15016936007446be0100000031c0833d19a4360000740cf00fb135df683600750beb230fb135d4683600741a488d3dcb6836004881ec80000000e89f110c004881c480000000488915b96836008b05bb6836008305a86836000185c0744383f801747783f8020f848e00000083f8030f844201000083f8040f849801000083f8050f84ad01000083f8060f84c701000083f8070f84bf0100000f1f440000f4ebfd31c0b9100000004889e7f348ab31d24889e6bf01000000c7054c6836000100000048c7042420000000e82fefffff8b053968360083f801758931ffc7052868360002000000e8730f04008b051d68360083f8020f8572ffffff832d0168360001c7050368360000000000754148c705ee67360000000000833d0fa3360000740bf0ff0dd6673600750aeb22ff0dcc673600741a488d3dc36736004881ec80000000e8c7100c004881c480000000bf06000000e806ebffff64488b142510000000483b159e6736007446be0100000031c0833db6a2360000740cf00fb1357c673600750beb230fb13571673600741a488d3d686736004881ec80000000e83c100c004881c4800000004889155667360083054b67360001488d94248000000031c0b913000000c7053e673600040000004889d7488db280000000f348ab48c7c0ffffffff4889064883ee084839d675f431d2bf06000000c784240801000000000000e8c7edffff8b050167360083f8040f8568feffffc705ee66360005000000e839bd03008b05e366360083f8050f8553feffffbf06000000c705cb66360006000000e816eaffff8b05c066360083f8060f8539fefffff4bf7f000000c705a766360008000000e8a24008006690415741564155415455534883ec184885d248893c24488974240874474989d54989cc4c89c54531f6eb11660f1f44000074464c8d73014d39ee73284b8d1c2e488b3c2448d1eb4989df4d0faffc4c037c24084c89feffd585c079d54989dd4d39ee72d84883c41831c0
Function at 0x7f891fecb2d0 is sigprocmask
Function at 0x7f891fecaf30 is gsignal
Function at 0x7f891fecb2a0 is sigaction
Function at 0x7f891ff08230 is fcloseall
Function at 0x7f891fecaf30 is gsignal
Function at 0x7f891ff505e0 is _exit

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Comment by BRanganat** [comment]
I am using stable redis chart from helm and added a init container to add redisgraph.so, so that I can load that module while starting the redis cluster inside kubernetes.

Following is the info I get in the pod log in addition to what I have mentioned in the top.

INFO ==> ** Starting Redis **
1:C 16 Jul 2019 18:49:49.484 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 16 Jul 2019 18:49:49.484 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 16 Jul 2019 18:49:49.484 # Configuration loaded
1:M 16 Jul 2019 18:49:49.486 * Running mode=standalone, port=6379.
1:M 16 Jul 2019 18:49:49.486 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 16 Jul 2019 18:49:49.486 # Server initialized
1:M 16 Jul 2019 18:49:49.486 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 16 Jul 2019 18:49:49.488 * Thread pool created, using 4 threads.
1:M 16 Jul 2019 18:49:49.488 * Module 'graph' loaded from /data/redisgraph.so

redis-server: /redisgraph/src/module.c:55: RedisModule_OnLoad: Assertion `GrB_init(GrB_NONBLOCKING) == GrB_SUCCESS' failed.

**Comment by swilly22** [comment]
It seems like GraphBLAS failed to initialise, not sure why though, I'll add additional logging which will shad some light on the reason, I'll let you know when a new version is available and we'll try to continue from there.

**Comment by swilly22** [comment]
@BRanganat, just a quick debug question,
You're not trying to load RedisGraph into a redis-server which already running RedisGraph?

**Comment by swilly22** [comment]
@BRanganat I've just pushed a version which will log GraphBLAS initialisation error, can you please retry and share the log?
Thank you.

**Comment by BRanganat** [comment]
Below mentioned is the image I am using for redis,
        image: "docker.io/bitnami/redis:5.0.5-debian-9-r36"

On top of this I have the compiled code of RedisGraph repo into one of the volume and loading that using loadmodule in redis.conf. 
I will try with the latest RedisGraph repo and will let you know the result.

**Comment by BRanganat** [comment]
This time I didnt get much log but still failed.

INFO  ==> ** Starting Redis **
1:C 18 Jul 2019 13:53:06.278 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 18 Jul 2019 13:53:06.279 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 18 Jul 2019 13:53:06.279 # Configuration loaded
1:M 18 Jul 2019 13:53:06.281 * Running mode=standalone, port=6379.
1:M 18 Jul 2019 13:53:06.281 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 18 Jul 2019 13:53:06.281 # Server initialized
1:M 18 Jul 2019 13:53:06.281 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 18 Jul 2019 13:53:06.286 * <graph> Thread pool created, using 4 threads.
1:M 18 Jul 2019 13:53:06.286 * Module 'graph' loaded from /data/redisgraph.so
1:M 18 Jul 2019 13:53:06.286 # Module /data/redisgraph.so initialization failed. Module not loaded
1:M 18 Jul 2019 13:53:06.286 # Can't load module from /data/redisgraph.so: server aborting

**Comment by swilly22** [comment]
I no longer see GraphBLAS assertion, the log is a bit strange,
for once it says: `1:M 18 Jul 2019 13:53:06.286 * Module 'graph' loaded from /data/redisgraph.so`
but then `1:M 18 Jul 2019 13:53:06.286 # Module /data/redisgraph.so initialization failed. Module not loaded`

Can you please make sure you're not trying to load RedisGraph more than once?
Would you mind sharing your `redis.conf`?

**Comment by BRanganat** [comment]
On the below mentioned configmap, I have commented "appendonly yes" as it was throwing error saying AOF is not allowed for redisgraph. Also added the "loadmodule /data/redisgraph.so".

=======================================================
# Source: redis/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: redis
    chart: redis-8.1.3
    heritage: Tiller
    release: redis-cluster
  name: redis-cluster
data:
  redis.conf: |-
    # User-supplied configuration:
    # Enable AOF https://redis.io/topics/persistence#append-only-file
    # appendonly yes
    loadmodule /data/redisgraph.so
    # Disable RDB persistence, AOF persistence already enabled.
    save ""
  master.conf: |-
    dir /data
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
  replica.conf: |-
    dir /data
    slave-read-only yes
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
=====================================================

**Comment by swilly22** [comment]
@BRanganat thanks,
Would you mind removing `loadmodule /data/redisgraph.so` from `redis.conf`
starting Redis and posting the output of the `module list` command?

**Comment by haljin** [comment]
Hi, I have the same or similar problem. 

I'm trying to deploy in K8s using https://github.com/bitnami/charts/tree/master/bitnami/redis. I have build a custom image by doing 

```
FROM bitnami/redis:6.0.4-debian-10-r5 AS builder

USER root

RUN apt update && apt-get install -y build-essential cmake m4 automake peg libtool autoconf
RUN apt-get -y install git

RUN git clone --recurse-submodules -j8 https://github.com/RedisGraph/RedisGraph.git

RUN cd RedisGraph && make

FROM bitnami/redis:6.0.4-debian-10-r5

USER root
RUN apt update && apt-get install libgomp1
RUN mkdir -p /opt/redisgraph/
USER 1001

COPY --from=builder /RedisGraph/src/redisgraph.so /opt/redisgraph
```


Then I configure the chart with 

```
configmap: |-
  # Enable AOF https://redis.io/topics/persistence#append-only-file
  appendonly no
  # Disable RDB persistence, AOF persistence already enabled.
  save ""
  loadmodule /opt/redisgraph/redisgraph.so
```

and get:

```
 07:17:28.87 INFO  ==> ** Starting Redis **
1:C 09 Jun 2020 07:17:28.889 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 09 Jun 2020 07:17:28.889 # Redis version=6.0.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 09 Jun 2020 07:17:28.889 # Configuration loaded
1:M 09 Jun 2020 07:17:28.890 * Running mode=standalone, port=6379.
1:M 09 Jun 2020 07:17:28.890 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 09 Jun 2020 07:17:28.890 # Server initialized
1:M 09 Jun 2020 07:17:28.890 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 09 Jun 2020 07:17:28.896 * <graph> Entities limit per graph meta key set to 100000.
1:M 09 Jun 2020 07:17:28.897 * <graph> Thread pool created, using 16 threads.
1:M 09 Jun 2020 07:17:28.897 * Module 'graph' loaded from /opt/redisgraph/redisgraph.so
redis-server: /RedisGraph/src/module.c:81: RedisModule_OnLoad: Assertion `GxB_init(GrB_NONBLOCKING, rm_malloc, rm_calloc, rm_realloc, rm_free, true) == GrB_SUCCESS' failed.


=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 09 Jun 2020 07:17:28.898 # Redis 6.0.4 crashed by signal: 11
1:M 09 Jun 2020 07:17:28.898 # Crashed running the instruction at: 0x7f79d68dd611
1:M 09 Jun 2020 07:17:28.898 # Accessing address: (nil)
1:M 09 Jun 2020 07:17:28.898 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7f79d68dd611]

Backtrace:
/opt/bitnami/redis/bin/redis-server *:6379(logStackTrace+0x32)[0x5590ff8cee32]
/opt/bitnami/redis/bin/redis-server *:6379(sigsegvHandler+0x9e)[0x5590ff8cf50e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7f79d6a90730]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7f79d68dd611]
/lib/x86_64-linux-gnu/libc.so.6(+0x2240f)[0x7f79d68dd40f]
/lib/x86_64-linux-gnu/libc.so.6(+0x30102)[0x7f79d68eb102]
/opt/redisgraph/redisgraph.so(+0x1b0f81)[0x7f79d58e1f81]
/opt/bitnami/redis/bin/redis-server *:6379(moduleLoad+0xab)[0x5590ff901d5b]
/opt/bitnami/redis/bin/redis-server *:6379(moduleLoadFromQueue+0x33)[0x5590ff901ed3]
/opt/bitnami/redis/bin/redis-server *:6379(main+0x427)[0x5590ff881747]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7f79d68df09b]
/opt/bitnami/redis/bin/redis-server *:6379(_start+0x2a)[0x5590ff881a7a]

------ INFO OUTPUT ------
# Server
redis_version:6.0.4
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:152e33dc1238b01e
redis_mode:standalone
os:Linux 4.19.106-coreos x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0
process_id:1
run_id:8e5ec9aa602bcc1d646c6bbed4acbc3c18cc91b9
tcp_port:6379
uptime_in_seconds:0
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:14628744
executable:/opt/bitnami/redis/bin/redis-server
config_file:/opt/bitnami/redis/etc/redis.conf

# Clients
connected_clients:0
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:838832
used_memory_human:819.17K
used_memory_rss:0
used_memory_rss_human:0B
used_memory_peak:838832
used_memory_peak_human:819.17K
used_memory_peak_perc:inf%
used_memory_overhead:0
used_memory_startup:0
used_memory_dataset:838832
used_memory_dataset_perc:100.00%
allocator_allocated:0
allocator_active:0
allocator_resident:0
total_system_memory:67531702272
total_system_memory_human:62.89G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:-nan
allocator_frag_bytes:0
allocator_rss_ratio:-nan
allocator_rss_bytes:0
rss_overhead_ratio:-nan
rss_overhead_bytes:0
mem_fragmentation_ratio:-nan
mem_fragmentation_bytes:0
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1591687048
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:0
total_commands_processed:0
instantaneous_ops_per_sec:0
total_net_input_bytes:0
total_net_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0

# Replication
role:master
connected_slaves:0
master_replid:5647d7b4bef9fa291a5ce4180be66714f731aacb
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.041799
used_cpu_user:0.033874
used_cpu_sys_children:0.002410
used_cpu_user_children:0.004651

# Modules
module:name=graph,ver=999999,api=1,filters=0,usedby=[],using=[],options=[]

# Commandstats

# Cluster
cluster_enabled:0

# Keyspace

------ CLIENT LIST OUTPUT ------

------ REGISTERS ------
1:M 09 Jun 2020 07:17:28.898 # 
RAX:0000000000000000 RBX:0000000000000000
RCX:0000000000000000 RDX:0000000000000000
RDI:0000000000000002 RSI:00007fffa30f9710
RBP:00007f79d6a3fee0 RSP:00007fffa30f9830
R8 :0000000000000000 R9 :00007fffa30f9710
R10:0000000000000008 R11:0000000000000246
R12:00007f79d5daa547 R13:00007f79d5dab408
R14:0000000000000051 R15:00007fffa30f9d38
RIP:00007f79d68dd611 EFL:0000000000010246
CSGSFS:002b000000000033
1:M 09 Jun 2020 07:17:28.898 # (00007fffa30f983f) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.898 # (00007fffa30f983e) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.898 # (00007fffa30f983d) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.898 # (00007fffa30f983c) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.898 # (00007fffa30f983b) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.899 # (00007fffa30f983a) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.899 # (00007fffa30f9839) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.899 # (00007fffa30f9838) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.899 # (00007fffa30f9837) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.899 # (00007fffa30f9836) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.899 # (00007fffa30f9835) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.899 # (00007fffa30f9834) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.899 # (00007fffa30f9833) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.899 # (00007fffa30f9832) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.899 # (00007fffa30f9831) -> 0000000000000000
1:M 09 Jun 2020 07:17:28.899 # (00007fffa30f9830) -> 0000000000000020

------ MODULES INFO OUTPUT ------

------ FAST MEMORY TEST ------
*** Preparing to test memory region 5590ffa19000 (2277376 bytes)
*** Preparing to test memory region 559100392000 (389120 bytes)
*** Preparing to test memory region 7f79ccf21000 (8388608 bytes)
*** Preparing to test memory region 7f79cd722000 (8388608 bytes)
*** Preparing to test memory region 7f79cdf23000 (8388608 bytes)
*** Preparing to test memory region 7f79ce724000 (8388608 bytes)
*** Preparing to test memory region 7f79cef25000 (8388608 bytes)
*** Preparing to test memory region 7f79cf726000 (8388608 bytes)
*** Preparing to test memory region 7f79cff27000 (8388608 bytes)
*** Preparing to test memory region 7f79d0728000 (8388608 bytes)
*** Preparing to test memory region 7f79d0f29000 (8388608 bytes)
*** Preparing to test memory region 7f79d172a000 (8388608 bytes)
*** Preparing to test memory region 7f79d1f2b000 (8388608 bytes)
*** Preparing to test memory region 7f79d272c000 (8388608 bytes)
*** Preparing to test memory region 7f79d2f2d000 (8388608 bytes)
*** Preparing to test memory region 7f79d372e000 (8388608 bytes)
*** Preparing to test memory region 7f79d3f2f000 (8388608 bytes)
*** Preparing to test memory region 7f79d4730000 (8388608 bytes)
*** Preparing to test memory region 7f79d4f31000 (8388608 bytes)
*** Preparing to test memory region 7f79d5ffd000 (12288 bytes)
*** Preparing to test memory region 7f79d6000000 (8388608 bytes)
*** Preparing to test memory region 7f79d68b7000 (16384 bytes)
*** Preparing to test memory region 7f79d6a78000 (24576 bytes)
*** Preparing to test memory region 7f79d6a9b000 (16384 bytes)
*** Preparing to test memory region 7f79d6d84000 (16384 bytes)
*** Preparing to test memory region 7f79d6fae000 (12288 bytes)
*** Preparing to test memory region 7f79d6fda000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: abort (base: 0x7f79d68dd414)
Module: /lib/x86_64-linux-gnu/libc.so.6 (base 0x7f79d68bb000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x7f79d68dd414 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
1:M 09 Jun 2020 07:17:29.540 # dump of function (hexdump of 637 bytes):
4881ec2801000064488b042528000000488984241801000031c064488b142510000000483915faa819007444be01000000833da4e2190000740cf00fb135daa81900750beb230fb135cfa81900741a488d3dc6a819004881ec80000000e88a420e004881c480000000488915b4a81900ff05aaa81900833dafa81900007536c705a3a8190001000000b81000000048ffc84889e64883f8ff740a48c704c600000000ebea31d2bf0100000048830c2420e8875501008b0571a8190083f8010f85bd000000ff0d56a81900c70558a8190000000000754148c70543a8190000000000833df4e1190000740bf0ff0d2ba81900750aeb22ff0d21a81900741a488d3d18a819004881ec80000000e80c420e004881c480000000bf06000000e87b51010064488b142510000000483915f3a719007446be0100000031c0833d9be1190000740cf00fb135d1a71900750beb230fb135c6a71900741a488d3dbda719004881ec80000000e881410e004881c480000000488915aba71900ff05a1a71900eb0583f8027547488db4248000000031c0b9260000004883caffc70589a71900030000004889f7f3abb810000000488914c648ffc875f731d2bf06000000c784240801000000000000e83f540100833d58a71900037514c7054ca7190004000000bf06000000e8b2500100833d3ba7190004750bc7052fa7190005000000f4833d27a71900057514c7051ba7190006000000bf7f000000e871430a00f4ebfde8ddfdffffe8d8fdffffe8d3fdffffe8cefdffffe8c9fdffffe8c4fdffffe8bffdffffe8bafdffff836374ebf70300800000753f488b9388000000836a0401753248c7420800000000833d6ee01900007407f0ff0a7506eb1aff0a7416488d
Function at 0x7f79d68f2a50 is sigprocmask
Function at 0x7f79d68f26b0 is gsignal
Function at 0x7f79d68f2a20 is sigaction
Function at 0x7f79d69819a0 is _exit
Function at 0x7f79d68dd414 is abort

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/antirez/redis/issues

  Suspect RAM error? Use redis-server --test-memory to verify it.
```

The funny thing is, if I instead of using the config modify the container entrypoint with 

```
master:
  persistence:
    enabled: false
  command: redis-server --loadmodule /opt/bitnami/redis/redisgraph.so
```

it works just fine. Any ideas?

**Comment by jeffreylovitz** [comment]
Hi @haljin,

It looks like your configuration is trying to load the RedisGraph module twice. In your output, we see:
```
1:M 09 Jun 2020 07:17:28.896 * <graph> Entities limit per graph meta key set to 100000.
1:M 09 Jun 2020 07:17:28.897 * <graph> Thread pool created, using 16 threads.
1:M 09 Jun 2020 07:17:28.897 * Module 'graph' loaded from /opt/redisgraph/redisgraph.so
redis-server: /RedisGraph/src/module.c:81: RedisModule_OnLoad: Assertion `GxB_init(GrB_NONBLOCKING, rm_malloc, rm_calloc, rm_realloc, rm_free, true) == GrB_SUCCESS' failed.
```
The first two of these logging lines occur after `GxB_init` has been called successfully. The module then tries to load again, and the assertion on `GxB_init` fails because that call should be made exactly once.

I can reproduce the same failure with:
`redis-server --loadmodule src/redisgraph.so --loadmodule src/redisgraph.so`

Can you determine why your configuration is loading the module multiple times?

(As a sidenote, I believe you want to specify `appendonly yes`!)

**Comment by haljin** [comment]
Looks like doing

```
master:
  configmap: |-
    # Disable all persistence
    appendonly no
    save ""
    loadmodule /opt/redisgraph/redisgraph.so
```
works fine, maybe the helm chart somehow templates the config twice into the config file when using `configmap` but not with `master.configmap` and `slave.configmap`

Thanks for the hint!

As for `appendonly` does that affect the master/slave replication? The pod does not have any persistent storage so the file would disappear in case of failure anyway which is probably what we want for our use case.

**Comment by jeffreylovitz** [comment]
Regarding `appendonly`, it sounds like I misunderstood your setup! Persistency modes in general should not have an effect on replication; you should be free to disable them both.

**Comment by swilly22** [comment]
Trying to load RedisGraph multiple times within a single Redis-Server will cause GraphBLAS to fail while initialising,  as such loading the module a second time to fail and the server will shutdown.

**Comment by MiriChanuka** [comment]
איך עוצרים בסופו של דבר את זה שזה רץ פעמים?
