### ISSUE TITLE
RedisGraph always crashes for longer MATCH elements (Longer queries) #726

### ISSUE THREAD

**Issue by SaiprasadKrishnamurthy** [RedisGraph/RedisGraph#738]
This is the original issue:

[https://github.com/RedisGraph/RedisGraph/issues/726](url)

This still crashing for this query:

` MATCH (p1)-[c1:connected_to]->(p2),(p2)-[c2:connected_to]->(p3),(p3)-[c3:connected_to]->(p2),(p2)-[c4:connected_to]->(p4),(p4)-[c5:connected_to]->(p5) WHERE 1=1  AND p1 <> p2 AND p1 <> p3 AND p1 <> p4 AND p1 <> p5 AND p2 <> p3 AND p2 <> p4 AND p2 <> p5 AND p3 <> p4 AND p3 <> p5 AND p4 <> p5 RETURN DISTINCT p1,p2,p3,p4,p5,c1,c2,c3,c4,c5`

I guess the cycle detection still isn't 'crash-safe' ?

**Comment by SaiprasadKrishnamurthy** [comment]
#726

**Comment by SaiprasadKrishnamurthy** [comment]
HEre is the log for this crash:


```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 14 Nov 2019 13:35:58.941 # Redis 5.0.6 crashed by signal: 11
1:M 14 Nov 2019 13:35:58.941 # Crashed running the instruction at: 0x7f2dbbc2f611
1:M 14 Nov 2019 13:35:58.941 # Accessing address: (nil)
1:M 14 Nov 2019 13:35:58.941 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7f2dbbc2f611]

Backtrace:
redis-server *:6379(logStackTrace+0x32)[0x55ef7eb4e452]
redis-server *:6379(sigsegvHandler+0x9e)[0x55ef7eb4eb2e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7f2dbbde0730]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7f2dbbc2f611]
/lib/x86_64-linux-gnu/libc.so.6(+0x2240f)[0x7f2dbbc2f40f]
/lib/x86_64-linux-gnu/libc.so.6(+0x30102)[0x7f2dbbc3d102]
/usr/lib/redis/modules/redisgraph.so(NewExecutionPlan+0x142f)[0x7f2db93b430f]
/usr/lib/redis/modules/redisgraph.so(Graph_Query+0x2fc)[0x7f2db93aed2c]
/usr/lib/redis/modules/redisgraph.so(+0x18f62d)[0x7f2db93d662d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7f2dbbdd5fa3]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f2dbbd064cf]

------ INFO OUTPUT ------
# Server
redis_version:5.0.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:24cefa6406f92a1f
redis_mode:standalone
os:Linux 3.10.0-862.11.6.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0
process_id:1
run_id:309db041e51fe8a733cae37fd0813d9181b6cda5
tcp_port:6379
uptime_in_seconds:53
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:13457470
executable:/data/redis-server
config_file:

# Clients
connected_clients:17
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:1

# Memory
used_memory:2887216
used_memory_human:2.75M
used_memory_rss:5062656
used_memory_rss_human:4.83M
used_memory_peak:2887216
used_memory_peak_human:2.75M
used_memory_peak_perc:177.18%
used_memory_overhead:1111902
used_memory_startup:791384
used_memory_dataset:1775314
used_memory_dataset_perc:84.71%
allocator_allocated:1389312
allocator_active:1638400
allocator_resident:4583424
total_system_memory:4125224960
total_system_memory_human:3.84G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.18
allocator_frag_bytes:249088
allocator_rss_ratio:2.80
allocator_rss_bytes:2945024
rss_overhead_ratio:1.10
rss_overhead_bytes:479232
mem_fragmentation_ratio:4.29
mem_fragmentation_bytes:3883576
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:320446
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:7
rdb_bgsave_in_progress:0
rdb_last_save_time:1573738505
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:17
total_commands_processed:31
instantaneous_ops_per_sec:0
total_net_input_bytes:2318
total_net_output_bytes:772
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:8
keyspace_misses:1
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:569bd31bddf40731b72f38d74d18f8fa449a53ed
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.061411
used_cpu_user:0.111656
used_cpu_sys_children:0.005538
used_cpu_user_children:0.000000

# Commandstats
cmdstat_graph.QUERY:calls=5,usec=2196,usec_per_call=439.20
cmdstat_ping:calls=5,usec=3,usec_per_call=0.60
cmdstat_graph.DELETE:calls=1,usec=33,usec_per_call=33.00
cmdstat_auth:calls=17,usec=17,usec_per_call=1.00
cmdstat_exec:calls=1,usec=2181,usec_per_call=2181.00
cmdstat_multi:calls=1,usec=0,usec_per_call=0.00
cmdstat_config:calls=1,usec=2,usec_per_call=2.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=4 addr=62.253.180.155:39202 fd=8 name= age=45 idle=39 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=config
id=5 addr=51.143.160.211:51262 fd=9 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=6 addr=51.143.160.211:45547 fd=10 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=7 addr=51.143.160.211:58802 fd=11 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=8 addr=51.143.160.211:23698 fd=12 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=9 addr=51.143.160.211:56046 fd=13 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=10 addr=51.143.160.211:35325 fd=14 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=11 addr=51.143.160.211:38247 fd=15 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=17 addr=51.143.160.211:40770 fd=21 name= age=23 idle=23 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=18 addr=51.143.160.211:48617 fd=22 name= age=23 idle=23 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=19 addr=51.143.160.211:41364 fd=23 name= age=23 idle=23 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=20 addr=51.143.160.211:24500 fd=24 name= age=23 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY
id=12 addr=51.143.160.211:1135 fd=16 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=13 addr=51.143.160.211:20310 fd=17 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=14 addr=51.143.160.211:23398 fd=18 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=15 addr=51.143.160.211:53638 fd=19 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth
id=16 addr=51.143.160.211:44353 fd=20 name= age=24 idle=24 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=auth

------ REGISTERS ------
1:M 14 Nov 2019 13:35:58.947 #
RAX:0000000000000000 RBX:0000000000000000
RCX:0000000000000000 RDX:0000000000000000
RDI:0000000000000002 RSI:00007f2db9213120
RBP:00007f2dbbd91ee0 RSP:00007f2db9213240
R8 :0000000000000000 R9 :00007f2db9213120
R10:0000000000000008 R11:0000000000000246
R12:00007f2db99e5b48 R13:00007f2db99e241e
R14:0000000000000152 R15:00007f2db02037b0
RIP:00007f2dbbc2f611 EFL:0000000000010246
CSGSFS:0000000000000033
1:M 14 Nov 2019 13:35:58.947 # (00007f2db921324f) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db921324e) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db921324d) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db921324c) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db921324b) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db921324a) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db9213249) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db9213248) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db9213247) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db9213246) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db9213245) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db9213244) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db9213243) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db9213242) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db9213241) -> 0000000000000000
1:M 14 Nov 2019 13:35:58.947 # (00007f2db9213240) -> 0000000000000020

------ FAST MEMORY TEST ------
1:M 14 Nov 2019 13:35:58.947 # Bio thread for job type #0 terminated
1:M 14 Nov 2019 13:35:58.949 # Bio thread for job type #1 terminated
1:M 14 Nov 2019 13:35:58.956 # Bio thread for job type #2 terminated
*** Preparing to test memory region 55ef7ec7b000 (2248704 bytes)
*** Preparing to test memory region 55ef7fc96000 (212992 bytes)
*** Preparing to test memory region 7f2db0000000 (2179072 bytes)
*** Preparing to test memory region 7f2db6a00000 (8388608 bytes)
*** Preparing to test memory region 7f2db7200000 (4194304 bytes)
*** Preparing to test memory region 7f2db7794000 (8388608 bytes)
*** Preparing to test memory region 7f2db7f94000 (2621440 bytes)
*** Preparing to test memory region 7f2db8215000 (8388608 bytes)
*** Preparing to test memory region 7f2db8a16000 (8388608 bytes)
*** Preparing to test memory region 7f2db9bfa000 (12288 bytes)
*** Preparing to test memory region 7f2db9bfe000 (8388608 bytes)
*** Preparing to test memory region 7f2dba3ff000 (8388608 bytes)
*** Preparing to test memory region 7f2dbac00000 (8388608 bytes)
*** Preparing to test memory region 7f2dbb400000 (8388608 bytes)
*** Preparing to test memory region 7f2dbbc07000 (24576 bytes)
*** Preparing to test memory region 7f2dbbdca000 (16384 bytes)
*** Preparing to test memory region 7f2dbbdeb000 (16384 bytes)
*** Preparing to test memory region 7f2dbbf81000 (8192 bytes)
*** Preparing to test memory region 7f2dbbf84000 (4096 bytes)
*** Preparing to test memory region 7f2dbbfae000 (4096 bytes)

```

**Comment by swilly22** [comment]
@SaiprasadKrishnamurthy, you're right, sorry about that, will investigate.

**Comment by swilly22** [comment]
@SaiprasadKrishnamurthy fix has been merged to the `master` branch, should be available on docker hub soon enough.

**Comment by SaiprasadKrishnamurthy** [comment]
This still crashes for this query. But interestingly, nothing in the logs.

`MATCH (p1)-[c1:connected_to]->(p2),(p2)-[c2:connected_to]->(p3),(p3)-[c3:connected_to]->(p4),(p4)-[c4:connected_to]->(p1),(p1)-[c5:connected_to]->(p5),(p5)-[c6:connected_to]->(p6),(p6)-[c7:connected_to]->(p2),(p2)-[c8:connected_to]->(p7),(p7)-[c9:connected_to]->(p8),(p8)-[c10:connected_to]->(p6),(p6)-[c11:connected_to]->(p2),(p2)-[c12:connected_to]->(p3),(p3)-[c13:connected_to]->(p9),(p9)-[c14:connected_to]->(p7) WHERE 1=1  AND p1 <> p2 AND p1 <> p3 AND p1 <> p4 AND p1 <> p5 AND p1 <> p6 AND p1 <> p7 AND p1 <> p8 AND p1 <> p9 AND p2 <> p3 AND p2 <> p4 AND p2 <> p5 AND p2 <> p6 AND p2 <> p7 AND p2 <> p8 AND p2 <> p9 AND p3 <> p4 AND p3 <> p5 AND p3 <> p6 AND p3 <> p7 AND p3 <> p8 AND p3 <> p9 AND p4 <> p5 AND p4 <> p6 AND p4 <> p7 AND p4 <> p8 AND p4 <> p9 AND p5 <> p6 AND p5 <> p7 AND p5 <> p8 AND p5 <> p9 AND p6 <> p7 AND p6 <> p8 AND p6 <> p9 AND p7 <> p8 AND p7 <> p9 AND p8 <> p9 RETURN DISTINCT p1,p2,p3,p4,p5,p6,p7,p8,p9,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12,c13,c14

`

**Comment by SaiprasadKrishnamurthy** [comment]
Looks like this fix has broken even the queries that used to work before.

`MATCH (p1)-[c1:connected_to]->(p2),(p2)-[c2:connected_to]->(p3),(p3)-[c3:connected_to]->(p4),(p4)-[c4:connected_to]->(p1),(p1)-[c5:connected_to]->(p4),(p4)-[c6:connected_to]->(p5) WHERE 1=1  AND p1 <> p2 AND p1 <> p3 AND p1 <> p4 AND p1 <> p5 AND p2 <> p3 AND p2 <> p4 AND p2 <> p5 AND p3 <> p4 AND p3 <> p5 AND p4 <> p5 RETURN DISTINCT p1,p2,p3,p4,p5,c1,c2,c3,c4,c5,c6`


Here is the crash log:
```
1:M 17 Nov 2019 19:33:10.670 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 17 Nov 2019 19:33:10.670 # Server initialized
1:M 17 Nov 2019 19:33:10.670 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 17 Nov 2019 19:33:10.676 * <graph> Thread pool created, using 2 threads.
1:M 17 Nov 2019 19:33:10.676 * Module 'graph' loaded from /usr/lib/redis/modules/redisgraph.so
1:M 17 Nov 2019 19:33:10.676 * Ready to accept connections
redis-server: /redisgraph/src/arithmetic/algebraic_expression.c:435: _AlgebraicExpression_FromPath: Assertion `path && path_len > 0' failed.


=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 17 Nov 2019 19:34:25.993 # Redis 5.0.6 crashed by signal: 11
1:M 17 Nov 2019 19:34:25.993 # Crashed running the instruction at: 0x7fee8d998611
1:M 17 Nov 2019 19:34:25.993 # Accessing address: (nil)
1:M 17 Nov 2019 19:34:25.993 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7fee8d998611]

Backtrace:
redis-server *:6379(logStackTrace+0x32)[0x56435fcc1452]
redis-server *:6379(sigsegvHandler+0x9e)[0x56435fcc1b2e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12730)[0x7fee8db49730]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x1fd)[0x7fee8d998611]
/lib/x86_64-linux-gnu/libc.so.6(+0x2240f)[0x7fee8d99840f]
/lib/x86_64-linux-gnu/libc.so.6(+0x30102)[0x7fee8d9a6102]
/usr/lib/redis/modules/redisgraph.so(+0x1647df)[0x7fee8afa97df]
/usr/lib/redis/modules/redisgraph.so(+0x16c58a)[0x7fee8afb158a]
/usr/lib/redis/modules/redisgraph.so(NewExecutionPlan+0x3c0)[0x7fee8afb24a0]
/usr/lib/redis/modules/redisgraph.so(Graph_Query+0x2fc)[0x7fee8afadf2c]
/usr/lib/redis/modules/redisgraph.so(+0x19122d)[0x7fee8afd622d]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7fa3)[0x7fee8db3efa3]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7fee8da6f4cf]

------ INFO OUTPUT ------
# Server
redis_version:5.0.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:24cefa6406f92a1f
redis_mode:standalone
os:Linux 3.10.0-862.11.6.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0
process_id:1
run_id:1b4c8efbb64a4b79dc841d19e6139367229f20e5
tcp_port:6379
uptime_in_seconds:75
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:13738177
executable:/data/redis-server
config_file:

# Clients
connected_clients:2
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:1

# Memory
used_memory:2746552
used_memory_human:2.62M
used_memory_rss:6295552
used_memory_rss_human:6.00M
used_memory_peak:2746552
used_memory_peak_human:2.62M
used_memory_peak_perc:101.85%
used_memory_overhead:858072
used_memory_startup:791384
used_memory_dataset:1888480
used_memory_dataset_perc:96.59%
allocator_allocated:2823744
allocator_active:3194880
allocator_resident:6115328
total_system_memory:4125224960
total_system_memory_human:3.84G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.13
allocator_frag_bytes:371136
allocator_rss_ratio:1.91
allocator_rss_bytes:2920448
rss_overhead_ratio:1.03
rss_overhead_bytes:180224
mem_fragmentation_ratio:2.33
mem_fragmentation_bytes:3599000
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:66616
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:66
rdb_bgsave_in_progress:0
rdb_last_save_time:1574019190
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:8
total_commands_processed:81
instantaneous_ops_per_sec:44
total_net_input_bytes:18450
total_net_output_bytes:20340
instantaneous_input_kbps:10.78
instantaneous_output_kbps:5.04
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:126
keyspace_misses:1
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:0bd18cb5f347184da0b96c61df5c63a9946e1bb7
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.073094
used_cpu_user:0.104925
used_cpu_sys_children:0.000000
used_cpu_user_children:0.005194

# Commandstats
cmdstat_config:calls=1,usec=2,usec_per_call=2.00
cmdstat_exec:calls=1,usec=23111,usec_per_call=23111.00
cmdstat_auth:calls=7,usec=9,usec_per_call=1.29
cmdstat_graph.DELETE:calls=1,usec=26,usec_per_call=26.00
cmdstat_multi:calls=1,usec=1,usec_per_call=1.00
cmdstat_ping:calls=5,usec=1,usec_per_call=0.20
cmdstat_graph.QUERY:calls=64,usec=23085,usec_per_call=360.70
cmdstat_command:calls=1,usec=1136,usec_per_call=1136.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=1,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=9 addr=86.0.246.122:50398 fd=8 name= age=17 idle=9 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=config
id=11 addr=51.143.160.211:58709 fd=9 name= age=0 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=graph.QUERY

------ REGISTERS ------
1:M 17 Nov 2019 19:34:25.994 # 
RAX:0000000000000000 RBX:0000000000000000
RCX:0000000000000000 RDX:0000000000000000
RDI:0000000000000002 RSI:00007fee8ae41fc0
RBP:00007fee8dafaee0 RSP:00007fee8ae420e0
R8 :0000000000000000 R9 :00007fee8ae41fc0
R10:0000000000000008 R11:0000000000000246
R12:00007fee8b5e4508 R13:00007fee8b5e478c
R14:00000000000001b3 R15:00007fee88c19040
RIP:00007fee8d998611 EFL:0000000000010246
CSGSFS:0000000000000033
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420ef) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420ee) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420ed) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420ec) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420eb) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420ea) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420e9) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420e8) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420e7) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420e6) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420e5) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420e4) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420e3) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420e2) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420e1) -> 0000000000000000
1:M 17 Nov 2019 19:34:25.994 # (00007fee8ae420e0) -> 0000000000000020

------ FAST MEMORY TEST ------
1:M 17 Nov 2019 19:34:25.994 # Bio thread for job type #0 terminated
1:M 17 Nov 2019 19:34:25.995 # Bio thread for job type #1 terminated
1:M 17 Nov 2019 19:34:25.995 # Bio thread for job type #2 terminated
*** Preparing to test memory region 56435fdee000 (2248704 bytes)
*** Preparing to test memory region 564360a95000 (2310144 bytes)
*** Preparing to test memory region 7fee84000000 (2179072 bytes)
*** Preparing to test memory region 7fee88c00000 (4194304 bytes)
*** Preparing to test memory region 7fee890c3000 (8388608 bytes)
*** Preparing to test memory region 7fee898c3000 (5767168 bytes)
*** Preparing to test memory region 7fee89e44000 (8388608 bytes)
*** Preparing to test memory region 7fee8a645000 (8388608 bytes)
*** Preparing to test memory region 7fee8b7fa000 (12288 bytes)
*** Preparing to test memory region 7fee8b7fe000 (8388608 bytes)
*** Preparing to test memory region 7fee8bfff000 (8388608 bytes)
*** Preparing to test memory region 7fee8c800000 (8388608 bytes)
*** Preparing to test memory region 7fee8d000000 (8388608 bytes)
*** Preparing to test memory region 7fee8d970000 (24576 bytes)
*** Preparing to test memory region 7fee8db33000 (16384 bytes)
*** Preparing to test memory region 7fee8db54000 (16384 bytes)
*** Preparing to test memory region 7fee8dcea000 (8192 bytes)
*** Preparing to test memory region 7fee8dced000 (4096 bytes)
*** Preparing to test memory region 7fee8dd17000 (4096 bytes)
```

**Comment by SaiprasadKrishnamurthy** [comment]
Hi, any luck with this issue?

**Comment by swilly22** [comment]
No, I've put it on hold for now, sorry, we'll have to get back to it later on.
